name: widget_to_image_example
description: Demonstrates how to use the widget_to_image package.

publish_to: none

version: 1.0.1

environment:
  sdk: '>=3.1.0-10.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  widget_to_image:
    path: ../

flutter:
  uses-material-design: true
